defaultEntryPoints = ["websecure"]
logLevel = "DEBUG"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    defaultRule = "Host(`localhost`)"
    watch = true
    exposedByDefault = false

[accessLog]

[api]
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.le]
    [certificatesResolvers.le.acme]
      email = "admin@example.com"
      storage = "/letsencrypt/acme.json"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"

      [certificatesResolvers.le.acme.httpChallenge]
        entryPoint = "web"
